# Generated by Django 4.0 on 2022-02-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
