# Generated by Django 4.0 on 2022-02-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dapi', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
